### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-icoliz#1]
Really cool job @icoliz !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Don't use an element to resolve the counter, a good old constant will suffice ;) (this: <https://github.com/Adalab/modulo-2-evaluacion-intermedia-icoliz/blob/1e14f0b7df35f012a03ac3d8b331d107aa227e0a/js/main.js#L6-L7> )
- [x] Watch out for constant names used to save DOM references... Do we want to use the DOM reference or that DOM element content (innerHTML/value)?

### JavaScript: advanced

- [x] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### Good practices

- [x] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Add a reset button that cleans the select, the counter and writes the initial feedback
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by igarridomorillas** [comment]
That's perfect!
